shared:
  image: node:14
jobs:
  test1:
    requires: [ ~commit ]
    steps:
      - test: echo "test"
  test2:
    requires: [ ~commit ]
    steps:
      - test: exit 1
  test3:
    requires: [ ~commit ]
    steps:
      - test: echo "test"
  test4:
    requires: [ ~commit ]
    steps:
      - test: echo "test"
