shared:
  image: node:14
jobs:
  test1:
    requires: [ ~commit ]
    steps:
      - test: echo "test"
  test2:
    requires: [ test1 ]
    steps:
      - test: echo "test"
  test3:
    requires: [ test2 ]
    steps:
      - test: echo "test"
  foo:
    requires: [ test3 ]
    steps:
      - test: echo "test"
  test4:
    requires: [ foo ]
    steps:
      - test: echo "test"
